### ISSUE TITLE
Add training script availability

### ISSUE THREAD

**Issue by prassanna-ravishankar** [Vaibhavs10/open-tts-tracker#10]
Would be useful to have a section on training scripts and whether
- Full training script is available
- Fine tuning script is available

Additionally, it would be useful to have an idea if data for training is publicly available

**Comment by Vaibhavs10** [comment]
Hi @prassanna-ravishankar - This seems quite niche but generally, if fine-tuning code is available you can just do a random init and fine-tune as well right?
