### ISSUE TITLE
[Question] VITS/MMS-TTS also uses a GPL phonimiser? 

### ISSUE THREAD

**Issue by shivammehta25** [Vaibhavs10/open-tts-tracker#11]
I might be wrong but Isn't this part of the phonetisation in HF and also in the official VITS repository also GPL licensed? 

https://github.com/huggingface/transformers/blob/7142bdfa90a3526cfbed7483ede3afbef7b63939/src/transformers/models/vits/tokenization_vits.py#L199C3-L199C3

It may be that it isn't used but it is something that is not obvious to me thus the question. Would love some clarification about it.

**Comment by Vaibhavs10** [comment]
Oh definitely! I'll add the warning there too. 🚀

**Comment by Vaibhavs10** [comment]
Done in the latest commit. Feel free to re-open the issues in case it doesn't align well with what you intended. :)
