### ISSUE TITLE
About the License of HierSpeech++

### ISSUE THREAD

**Issue by sh-lee-prml** [Vaibhavs10/open-tts-tracker#13]
@Vaibhavs10 

Thanks for sharing our work!

We have changed the license to MIT License. (So please change our license information in ReadMe.MD!)

Now, you can use for commercial product. 

Please enjoy a high-quality zero-shot speech synthesis with a fast inference speed

Thanks!

**Comment by Pendrokar** [comment]
fixes #17

**Comment by Vaibhavs10** [comment]
Hi @sh-lee-prml - Thanks for updating the license. This change has been reflected in the README by @Pendrokar (Thank you Yanis 🙏)

I saw that y'all are also working on a more significant and potentially faster model. I'd love to explore collaboration options with you and how Hugging Face can help amplify the release for you. If this sounds interesting then can you please drop an email to me at vaibhav[at]huggingface[dot]co 🙏

Congratulations on such a brilliant project! ⚡

**Comment by Pendrokar** [comment]
Only mentioned the work and PR of @fakerybakery 👏

**Comment by Vaibhavs10** [comment]
Thanks! @fakerybakery ❤️
