### ISSUE TITLE
Add realtime info

### ISSUE THREAD

**Issue by Ahaeflig** [Vaibhavs10/open-tts-tracker#2]
Hi, I came across your list, thanks for sharing it.

I thought it would be useful if the table included information about whether each model can run in realtime or not and with what hardware. I might do a PR if I find the time.

Best,
H. A

**Comment by Pendrokar** [comment]
By realtime, you mean audio generation is close to real time or has audio streaming support?

**Comment by acidbubbles** [comment]
I think the intention is to identify their "speed". This is very useful information but hard to clearly define :)

**Comment by Pendrokar** [comment]
Indeed. As it depends on hardware. If a TTS supports audio streaming, that is would be more easily defined.

**Comment by Vaibhavs10** [comment]
Closing in favor of https://github.com/Vaibhavs10/open-tts-tracker/issues/14
