### ISSUE TITLE
Suggestion for Chronological Sorting of Projects for Enhancing Navigation

### ISSUE THREAD

**Issue by guan-yuan** [Vaibhavs10/open-tts-tracker#20]
Very helpful project. It would be great if the projects could be arranged in chronological order as much as possible, so it's easier to know which projects are the most recent. Thank you!

**Comment by smejjout** [comment]
See #9, feel free to make a pull request

**Comment by Vaibhavs10** [comment]
Closing in favor of: https://github.com/Vaibhavs10/open-tts-tracker/issues/9
