### ISSUE TITLE
Add RAD-TTS

### ISSUE THREAD

**Issue by egorsmkv** [Vaibhavs10/open-tts-tracker#21]

**Comment by Vaibhavs10** [comment]
Thanks for the suggestion. Added it in the most recent commit. Thanks! 🤗

**Comment by egorsmkv** [comment]
> Thanks for the suggestion. Added it in the most recent commit. Thanks! 🤗

I have made a RAD-TTS model for Ukrainian - https://github.com/egorsmkv/radtts-uk - you could add it to the repo as well
