### ISSUE TITLE
Add piper

### ISSUE THREAD

**Issue by noe** [Vaibhavs10/open-tts-tracker#5]
Piper (https://github.com/rhasspy/piper) :

> A fast, local neural text to speech system that sounds great and is optimized for the Raspberry Pi 4

* MIT license
* 2.4 stars on github.
* Weights: https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main
* Supported languages:
  * Arabic (ar_JO)
  * Catalan (ca_ES)
  * Czech (cs_CZ)
  * Danish (da_DK)
  * German (de_DE)
  * Greek (el_GR)
  * English (en_GB, en_US)
  * Spanish (es_ES, es_MX)
  * Finnish (fi_FI)
  * French (fr_FR)
  * Hungarian (hu_HU)
  * Icelandic (is_IS)
  * Italian (it_IT)
  * Georgian (ka_GE)
  * Kazakh (kk_KZ)
  * Luxembourgish (lb_LU)
  * Nepali (ne_NP)
  * Dutch (nl_BE, nl_NL)
  * Norwegian (no_NO)
  * Polish (pl_PL)
  * Portuguese (pt_BR, pt_PT)
  * Romanian (ro_RO)
  * Russian (ru_RU)
  * Serbian (sr_RS)
  * Swedish (sv_SE)
  * Swahili (sw_CD)
  * Turkish (tr_TR)
  * Ukrainian (uk_UA)
  * Vietnamese (vi_VN)
  * Chinese (zh_CN)

**Comment by phudtran** [comment]
Note: Piper also uses espeak-ng which is GPL licensed.

**Comment by noe** [comment]
Wow, I hadn't realised that, thanks for the heads up. I just found this issue with the discussion about the matter: https://github.com/rhasspy/piper/issues/93

If piper is to be added in this repo, then it would be nice to add a link to the mentioned issue.

**Comment by Vaibhavs10** [comment]
Thanks for the brilliant suggestion. I've added it in the latest commit + added the URL to the issue.
